### PR TITLE
Allow coaches to create rates.

### PR DESCRIPTION
**Pull request by martindale**

### CODE REVIEW

**Comment by martindale** [comment]
Alright, @unchaz / @unusualbob – the basic flow should be complete as of this pull request.  Test locally, but primarily;

- Users can now register; closes #18.
- Users can add games to their profile, as a coach or as a player.
- Users can now list an available time (Slots), with a start and an end time.
- Users can now select a specific Slot and attach a Booking.

**Comment by unChaz** [comment]
Awesome. There's still some links referencing /users. Also I had a crash every time I tried to make a booking:

/Users/chaz/workspace/coachie/coachie.js:33
          res.status( 303 ).redirect('/people/' + person.slug );
                                                        ^
TypeError: Cannot read property 'slug' of null

**Comment by martindale** [comment]
Keep your Games, but reset the other collections – I'm not able to reproduce the crash.  Does that fix it?

**Comment by unChaz** [comment]
Alot of stuff is just breaking because of references to user, so I can't even create a new user.

**Comment by martindale** [comment]
Are you sure you have the latest?  That's working for me as well.

**Comment by unChaz** [comment]
I pulled the latest, but there are still references to /users (the link to signup) and I still get

/Users/chaz/workspace/coachie/coachie.js:33
          res.status( 303 ).redirect('/people/' + person.slug );
                                                        ^
TypeError: Cannot read property 'slug' of null

Even after dropping all my collections but games.

**Pull request merged**
